package com.epam.rd.izh.soap.com.dataaccess.webservicesserver;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * The Text Casing Web Service, implemented with Visual DataFlex, provides functions to change text casing in different ways.
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TextCasing", targetNamespace = "http://www.dataaccess.com/webservicesserver/", wsdlLocation = "https://www.dataaccess.com/webservicesserver/TextCasing.wso?wsdl")
public class TextCasing
    extends Service
{

    private final static URL TEXTCASING_WSDL_LOCATION;
    private final static WebServiceException TEXTCASING_EXCEPTION;
    private final static QName TEXTCASING_QNAME = new QName("http://www.dataaccess.com/webservicesserver/", "TextCasing");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://www.dataaccess.com/webservicesserver/TextCasing.wso?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TEXTCASING_WSDL_LOCATION = url;
        TEXTCASING_EXCEPTION = e;
    }

    public TextCasing() {
        super(__getWsdlLocation(), TEXTCASING_QNAME);
    }

    public TextCasing(WebServiceFeature... features) {
        super(__getWsdlLocation(), TEXTCASING_QNAME, features);
    }

    public TextCasing(URL wsdlLocation) {
        super(wsdlLocation, TEXTCASING_QNAME);
    }

    public TextCasing(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TEXTCASING_QNAME, features);
    }

    public TextCasing(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TextCasing(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TextCasingSoapType
     */
    @WebEndpoint(name = "TextCasingSoap")
    public TextCasingSoapType getTextCasingSoap() {
        return super.getPort(new QName("http://www.dataaccess.com/webservicesserver/", "TextCasingSoap"), TextCasingSoapType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TextCasingSoapType
     */
    @WebEndpoint(name = "TextCasingSoap")
    public TextCasingSoapType getTextCasingSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.dataaccess.com/webservicesserver/", "TextCasingSoap"), TextCasingSoapType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TEXTCASING_EXCEPTION!= null) {
            throw TEXTCASING_EXCEPTION;
        }
        return TEXTCASING_WSDL_LOCATION;
    }

}
